sudo: false
language: node_js
cache:
  directories:
  - node_modules

node_js:
 - iojs
 - "0.10"
 - "0.12"

script: make test-travis
after_success:
 - ./scripts/travis/setup-git.sh
 - ./scripts/travis/merge-development-with-master.sh
